### ISSUE TITLE
library 'bit32' is incomplete

### ISSUE THREAD

**Issue by AngelMainXoXo** [SoupLord1/CC-phone-os-build#1]
After downloading the os and restarting my pocket computer it errored with the following message: "...modules/sha2/sha2.lua:166: library 'bit32' is incomplete". How do I fix this? Played on cc:tweaked fabric version  1.110.3 for minecraft 1.20.1

**Comment by SoupLord1** [comment]
> After downloading the os and restarting my pocket computer it errored with the following message: "...modules/sha2/sha2.lua:166: library 'bit32' is incomplete". How do I fix this? Played on cc:tweaked fabric version 1.110.3 for minecraft 1.20.1

It's because the emulator for vscode and ingame are different, If you still want to download the os I can upload the proper bit32 file

**Comment by SoupLord1** [comment]
Also, It's not supposed to be install directly from github I have an installer, I never expected anyone else to try and use it

**Comment by SoupLord1** [comment]
Here's the paste [Setup](https://pastebin.com/RWqY4mjC)

**Comment by AngelMainXoXo** [comment]
> Also, It's not supposed to be install directly from github I have an installer, I never expected anyone else to try and use it

I know, used it for downloading the os to my pocket computer

**Comment by AngelMainXoXo** [comment]
> > After downloading the os and restarting my pocket computer it errored with the following message: "...modules/sha2/sha2.lua:166: library 'bit32' is incomplete". How do I fix this? Played on cc:tweaked fabric version 1.110.3 for minecraft 1.20.1
> 
> It's because the emulator for vscode and ingame are different, If you still want to download the os I can upload the proper bit32 file

That would be nice

**Comment by SoupLord1** [comment]
It was meant for computers not pocket computers, I planned to make a resized version but never got to it

**Comment by SoupLord1** [comment]
> > > After downloading the os and restarting my pocket computer it errored with the following message: "...modules/sha2/sha2.lua:166: library 'bit32' is incomplete". How do I fix this? Played on cc:tweaked fabric version 1.110.3 for minecraft 1.20.1
> > 
> > It's because the emulator for vscode and ingame are different, If you still want to download the os I can upload the proper bit32 file
> 
> That would be nice

It was meant for computers not pocket computers, I planned to make a resized version but never got to it

I can try and fix the issue tommorrow if you're still interested in the project

**Comment by SoupLord1** [comment]
> After downloading the os and restarting my pocket computer it errored with the following message: "...modules/sha2/sha2.lua:166: library 'bit32' is incomplete". How do I fix this? Played on cc:tweaked fabric version 1.110.3 for minecraft 1.20.1

Here's the fix, [FIX](https://pastebin.com/mUQrjkUW) install that and reboot your computer

Also, default password is test
